### ISSUE TITLE
Line breaks on the Block?

### ISSUE THREAD

**Issue by weilinzung** [Loilo/node-symfony-style-console#13]
The default `io.success` & `io.error` has 2 line breaks on the top & 3 line breaks on the bottom? Can we have this equal?

I want to just have one line breaks on the top and bottom because the default is too big.

screenshot: https://i.imgur.com/UrCcDzl.png

thanks!

**Comment by Loilo** [comment]
Hey, thanks for your request. However, this project is an as-strict-as-possible port of Symfony's console styling and I'm not willing to deviate from that.

Or does the equivalent source code yiel different output in Symfony?

**Comment by weilinzung** [comment]
oh, ok. I am using it for Node & typescript with iTerm2 Build 3.2.7.
